name: pva-workflow-2
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "GitHub environment name to get the solution"
        required: true
        default: "DEV"
env:
  workflow_scripts_path: .github/workflows/scripts

jobs:
  check-environment-existence:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    steps:
      - name: check-environment-existence
        id: check-environment-existence
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.WORKFLOW_DISPATCH_TOKEN}}
          script: |
            const checkEnvironmentExistence = require('${{ env.workflow_scripts_path }}/js/checkEnvironmentExistence.js')
            const envInputString = '${{ github.event.inputs.environment }}'      
            await checkEnvironmentExistence({ github,context, envInputString })
             let res = await github.rest.repos.getAllEnvironments({
            owner: context.repo.owner,
            repo: context.repo.repo,
            });

  execute-pva-workflow-1:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    steps:
      - uses: actions/checkout@v3
      - name: run-pva-workflow-1
        id: run-pva-workflow-1
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.WORKFLOW_DISPATCH_TOKEN}}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'pva-workflow-1.yml',
              ref: '${{ github.ref }}',
              inputs: {
                environment: '${{ github.event.inputs.environment }}',
              }
            })

      - name: check-pva-workflow-1-status
        id: check-pva-workflow-1-status
        uses: actions/github-script@v6
        with:
          script: |
            let sleep = require('${{ env.workflow_scripts_path }}/js/Sleep.js')
            let currentStatus = null;
            sleep(2000)

            do {
              let workflowLog = await github.rest.actions.listWorkflowRuns({
                owner: context.repo.owner,
                repo: context.repo.repo,
                workflow_id: 'pva-workflow-1.yml',
                per_page: 1
              })

              if (workflowLog.data.total_count > 0) {
                currentStatus = workflowLog.data.workflow_runs[0].status
              }
              else {
                break
              }

              console.log('pva-workflow-1: ' + currentStatus)
              sleep(20000)
            } while (currentStatus != 'completed');

  sync-from-main-branch:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    needs: execute-pva-workflow-1
    steps:
      - uses: actions/checkout@v3

      - name: sync-from-main
        id: sync-from-main
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.WORKFLOW_DISPATCH_TOKEN}}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'sync-from-main.yml',
              ref: '${{ github.ref }}',
              inputs: {
                from_branch: '${{ secrets.SOURCE_BRANCH }}',
                to_branch: '${{ secrets.BRANCH_TO_CREATE }}'
              }
            })

      - name: check-sync-from-main-workflow-status
        id: check-sync-from-main-workflow-status
        uses: actions/github-script@v6
        with:
          script: |
            let sleep = require('${{ env.workflow_scripts_path }}/js/Sleep.js')
            let currentStatus = null;
            sleep(2000)

            do {
              let workflowLog = await github.rest.actions.listWorkflowRuns({
                owner: context.repo.owner,
                repo: context.repo.repo,
                workflow_id: 'sync-from-main.yml',
                per_page: 1
              })

              if (workflowLog.data.total_count > 0) {
                currentStatus = workflowLog.data.workflow_runs[0].status
              }
              else {
                break
              }

              console.log('sync-from-main: ' + currentStatus)
              sleep(20000)
            } while (currentStatus != 'completed');
