name: pva-workflow-3
on:
  workflow_dispatch:
    inputs:
      solution_name:
        description: "name of the Solution in Dataverse environment"
        required: true
        default: MicaSolution
      environment_url:
        description: "http endpoint of your Dataverse environment"
        required: true
        default: "https://orgea394ded.crm.dynamics.com/"
 
env:
  workflow_scripts_path: .github/workflows/scripts

jobs:
 delete-and-import-unmanaged-solution:
    runs-on: ubuntu-latest
    needs: sync-unmanaged-solution
    steps:
      - uses: actions/checkout@v2    
      - name: delete-and-import-unmanaged-solution
        id: delete-and-import-unmanaged-solution
        uses: actions/github-script@v5
        with:
          github-token: ${{secrets.WORKFLOW_DISPATCH_TOKEN}}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'delete-and-import-unmanaged-solution.yml',
              ref: '${{ github.ref }}',
              inputs: {
                solution_name: '${{ github.event.inputs.solution_name }}',
                environment_url: '${{ github.event.inputs.environment_url }}',
                ref: '${{ github.ref }}'
              }
            })
