name: sync-unmanaged-solution
on:
  workflow_dispatch:
    inputs:
      from_branch:
        description: "the ref(branch, commit, tag) that you want to import"
        required: true
        default: main
      to_branch:
        description: "branch"
        required: false

jobs:
  sync-branches:
    runs-on: ubuntu-latest
    name: Syncing branches
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Opening pull request
        id: pull
        uses: tretuna/sync-branches@1.4.0
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          FROM_BRANCH: ${{ github.event.inputs.from_branch }}
          TO_BRANCH: ${{ github.event.inputs.to_branch }}
